version: '3'
services:
  db:
    build:
      context: db
    image: pg-sql-server:0.0.1-snapshot
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: '!QAZxsw2'
      PG_DATABASE: ilt
      PG_USER: developer
      PG_PASSWORD: '!QAZxsw2'
      PG_TIMEZONE: 'Asia/Krasnoyarsk'
    networks:
      - ilt-network
    restart: always
  ilt-service:
    build:
      context: ilt-consaltin-service
    image: ilt-consaltin-service:0.0.1-snapshot
    ports:
      - "7777:7777"
    depends_on:
      - db
    networks:
      - ilt-network
volumes:
  db_data:

networks:
  ilt-network:
    driver: bridge