server:
  port: 7777
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ilt
    username: developer
    password: !QAZxsw2
    driver-class-name: org.postgresql.Driver

  flyway:
    user: developer
    password: !QAZxsw2
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/ilt