server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/ilt
    username: ilt
    password: !QAZxsw2
    driver-class-name: org.postgresql.Driver

  flyway:
    user: ilt
    password: !QAZxsw2
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/ilt