server:
  port: 8888
spring:
  datasource:
    username: "developer"
    password: "!QAZxsw2"
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5435/ilt"

  flyway:
    user: "developer"
    password: "!QAZxsw2"
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5435/ilt"